---
title: "There Votes the Neighborhood: Gentrification, Displacement, and Political Participation"
subtitle: ""
thanks: ##The authors thanks Many People for their comments on this project. All errors are our responsibility.##
author:
- Kevin Morris^[PhD Student, CUNY Graduate Center, Department of Sociology (kmorris@gradcenter.cuny.edu)]
institute: "Brennan Center for Justice"
date: "`r format(Sys.time(), '%B %d, %Y')`" 
output: word_document
bibliography: "gentrification_turnout.bib"
link-citations: yes
fontsize: 12pt
header-includes:
    - \usepackage{rotating}
    - \usepackage{setspace}
    - \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{A\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{A\arabic{figure}}}
    - \usepackage{lineno}
    # - \linenumbers
abstract: |
  TKTKTK
---
\pagenumbering{gobble}
\pagebreak
```{r setup, echo = F, message = F, warning = F}
knitr::opts_knit$set(root.dir = "..", dev = "cairo_pdf")
library(systemfit)
library(AER)
library(sandwich)
library(lmtest)
library(scales)
library(tidyverse)
library(extrafont)
library(kableExtra)
library(DescTools)
library(data.table)
library(stargazer)
loadfonts()
```
\pagenumbering{arabic}
\doublespacing
# Introduction {-}

TKTKTKTKTKTK

# Gentrification as a State Practice {-}

The latter half of the 20th century for the American metropolis was characterized by urban flight, disinvestment, and hyper-segregation. In the aftermath of the 1965 civil rights movement, many white Americans fled urban areas, both leading and following jobs out of these areas [@Jackson1985; @Sugrue1998]. While middle class white Americans were able to decamp for suburban areas, even relatively wealthy Black Americans were forced to remain in decaying urban neighborhoods thanks to racial steering from the real estate industry and racist lending practices by financial institutions [@Rothstein2017]. @Massey2003 documents many of the implications of this *de facto* segregation, demonstrating the vulnerability of Black Americans---regardless of class---to economic adversity. As @Taylor2019 shows, the consequences of these restrictive lending practices did more than simply keep Black Americans out of the suburbs: they also inhibited Black residents from buying property in their neighborhoods or investing in property that they did own. Declining tax bases and waning political capital meant that public services in urban areas deteriorated quickly, hastening the out migration of those who could do so [see, for instance, @Phillips-Fein2017].

In the late 20th and early 21st centuries, these patterns reversed as Americans began moving back to some urban areas. Increased capital investments [@Birch2009] formed an important part of this back-to-the-city movement [@Hyra2015]. As increasing numbers of highly-educated and highly-compensated Americans sought to live in cities such as San Francisco and New York, communities that had been marginalized (both economically and physically) for a generation or more found themselves residing in areas with increasing potential value. As Samuel Stein argues in *Capital City* [-@Stein2019], financial capitalists recognized the mismatch between the current and potential income being produced in urban neighborhoods. He explains: "Real estate speculators choose to invest in a particular location because they identify a gap between the rents that land currently offers and the potential future rents it might command if some action were taken" [@Stein2019, 49]. Stein argues, however, that gentrification is at heart a political issue; it cannot transpire without the state clearing the way for investors to exploit that value gap. Smith [-@Smith2002, 441, emphasis added] makes this point even more explicitly: "By the end of the twentieth century," he writes, "gentrification *fueled by a concerted and systematic partnership of public planning with public and private capital* had moved into the vacuum left by the end of liberal urban policy."

This analysis of the state-led nature of gentrification is echoed in the popular press, where journalists often draw links between state action and increased rents. When discussing the rezoning of the Inwood neighborhood in Manhattan, for instance, the *New York Times* wrote that "After the rezoning plan was announced in 2013, years before it was enacted, real estate investors swooped into Inwood and bought more than $610 million in properties" [@Haag2019]. Public infrastructure programs, such as the BeltLine Park in Atlanta, are also led by the state and feared by residents for their potentially displacing effect [@Lartey2018]. Whether the state is explicitly subsidizing development in an area by providing improved public goods or implicitly subsidizing it by allowing for higher-intensity development, the state's involvement is clear. It is perhaps unsurprising, then, that many communities where state investment has historically been virtually nonexistent are fighting back against plans that would increase financial investment in their neighborhoods [e.g. @Lees2018].

The state, then, is inherently involved in the gentrification of American cities. State (in)action led to under-investment in these neighborhoods in the 20th century, and state action is now paving the way for private interests to capitalize on that history. And yet, the existing work on gentrification has largely ignored how---or whether---residents hold the state accountable for their changed life circumstances. Scholars have instead focused on the non-state consequences of gentrification, asking questions primarily about whether gentrification leads to displacement [@Hwang2020], how it effects education [@Keels2013], whether it increases employment [@Meltzer2017], its effects on crime [@Papachristos2011], and other matters. While these questions certainly have merit, understanding whether residents turn to the ballot to contest gentrification is of key importance given the role of the state in its mechanics.

# The Potentially Politicizing Nature of Gentrification {-}

## Policy Threat {-}

A growing body of literature in political science and sociology documents how citizens respond when they face threatening circumstances. While sociologists have historically focused on "extra-institutional" political behavior such as protest and social movement participation, political scientists have often focused more narrowly on political *outcomes* [@Barrie2021]. Both disciplines, however, provide insights into how political behavior is shaped by government action.

Throughout this literature runs the notion of governmental or policy threat: namely, when individuals feel that they or a group to which they belong are being targeted by government policy, they can be mobilized to take action [@TamCho2006a]. Van Stekelenburg and Klandermans [-@vanStekelenburg2013, 897] explain: "The more people feel that interests of the group and/or principles that the group values are threatened, the angrier they are and the more they are prepared to take part in protest to protect their interests and principles and/or to express their anger." @Almeida2018 characterizes these threats from the state as "rights eroding" threats, noting that threats to abortion and welfare programs often spur citizens to take action. @Reese2011 similarly documents how citizens faced with President Bill Clinton's Personal Responsibility and Work Opportunity Reconciliation Act of 1996, which threatened to radically undermine the U.S.'s social safety net, were mobilized into resistance. Key to this mobilization is the understanding that group-level processes are at work: @Piven1979 and @Schlozman1979, for instance, document how workers become politically engaged when they understand their unemployment as a widespread phenomenon that demands collective government response and not an individual failure.

@Zepeda-Millan2016 offers key insight into how even "unconventional" political actors can be mobilized to participate under certain circumstances. He uses the case of Latinos in Fort Myers, Florida, to demonstrate these processes. In 2006, Americans across the country took to the streets to protest *The Border Protection, Antiterrorism, and Illegal Immigration Control Act of 2005* (H.R. 4437), widely considered to be discriminatory toward Latinos. The bill sought to change the penalty for being an undocumented immigrant from a misdemeanor to a felony, and to provide vast new resources for border enforcement. Zepeda-Millán [-@Zepeda-Millan2016, 270] shows how neighborhood context and the cultivation of shared Latino identities led "unconventional political actors---from local soccer league players and nannies to farmworkers and ethnic entrepreneurs---to utilize pre-existing neighborhood assets for the purpose of immigrant mass mobilization."

These policy threats have also been shown to induce citizens to cast ballots at higher rates. Ariel @White2016, for instance, documents how strict immigration enforcement led to higher turnout rates among Latinos in counties across the country. Similarly, @Towler2018 argues that Black Americans turned out at high rates in the 2016 president because of the threat posed to their community by Donald Trump. Tam Cho and colleagues [-@TamCho2006a, 978], in a study demonstrating higher turnout among Arab Americans who feel threatened, sum up: "A solid body of evidence... indicates that political mobilization is a direct response to the degree of threat and discrimination a group experiences."

Gentrification can be understood through this same lens; as discussed above, the state plays a central role in the facilitation of gentrification. Although @Thorpe2021 argues that scholars have not historically acknowledged the importance of law and policy in the easing of gentrification, the scholars and activists have long written about gentrification using the language of rights. Since Henri Lefebvre's 1968 *Le Droit à la Ville* [-@Lefebvre1968], scholars and activists have counterposed the demands of capital with citizens' "right to the city" and, more recently, "right to stay put" [see, for instance, @Hartman2002]. Insofar as residents understand gentrification as an infringements on their *right* to their home or community, it likely activates many of the same responses that have been identified in other contexts of policy threat. Given the highly racialized nature of contemporary gentrification [@Freeman2015], nonwhite residents may further feel targeted due to the racial identities of their communities.

@Betancur2002 explores how these processes play out in the context of West Town (a collection of neighborhoods in Chicago) in the early 1990s and 2000. Betancur notes that, "Concerned about improving the tax base, city hall did all it could to promote gentrification." Ultimately, "A crucial element at work in West Town was public-sector support for the processes and institutions that made use of public powers of social control to make life miserable for minority low-income residents" (806). Betancur argues that the state's role in gentrification was contested politically through both institutional and non-institutional means. Gentrification was a major issue in alderman elections in 1999, following the splitting of the area into 4 wards in the aftermath of the 1989 census. But Betancur also shows how the political process played out in non-institutional spaces as well. To take one example, "Puerto Ricans made great advances in controlling local schools, getting local institutions (e.g., hospitals and churches) to pay attention to their needs
and cultural and economic realities, promoting community identity and pride, and gaining respect from political forces" (802).

Similarly, @Martin2007a shows how communities in Atlanta, Georgia, resist political displacement in the face of gentrification. Worried about the rising numbers of newcomers to their neighborhoods, long-term residents created or invested in organizations to represent their interests. Martin describes how new and existing residents of the Belleview neighborhood struggled for the upper political hand: "For seven years, long-time residents and new residents engaged each other in a series of bitter conflicts over political influence. Through separate organizations, they challenged each other about new neighborhood amenities such as a neighborhood library, a grocery store, and streetscaping in the neighborhood business district. They also sparred over valid means
to control crime in the neighborhood, over appropriate neighborhood leadership, and even over the process of gentrification itself" (616). It is clear that, at least under certain circumstances, long-term residents in gentrifying neighborhoods are able to organize politically---in an electoral sense or otherwise---to contest the gentrification process.

## Social Cohesion {-}

While the policy threat literature indicates that gentrification might lead to *higher* turnout as a community feels itself threatened by the state and by real estate capital, other work indicates that gentrification could *reduce* turnout by undermining social solidarity within a neighborhood. In fact, the lone paper of which I am aware exploring the turnout effects of gentrification [@Knotts2006] comes to this conclusion, finding that turnout for long-term residents in gentrified neighborhoods in Atlanta was lower than long-term residents residing elsewhere. However, because they use only a single snapshot of the registered voter file and compare all voters in gentrified neighborhoods to all voters elsewhere, any causal interpretation of these results is suspect.

Despite limitations in their quantitative analysis, @Knotts2006 provides a helpful theoretical overview of how the neighborhood and social disruption that attends gentrification can reduce voter participation. This is in line with work such as @Levine2018, which investigated the influence of neighborhood stability---measured using home ownership rates, residential move rates, and median age---was positively associated with political participation in Boston.

More generally, individuals with stronger ties to their communities generally vote at higher rates. @Verba1995's civic voluntarism model indicates that voters' voluntary associations, churches, and workplaces provide them with the tools to participate in democracy. To be sure, political scientists have long argued that there is a social pressure to vote [e.g. @Riker1968], and there is evidence that citizens participate at higher rates when they fear the opprobrium of their neighbors. @Gerber2008 provides one famous example, in which potential voters were assigned to one of four treatment groups. Being reminded that voting is a civic duty, informing voters that their behavior would be studied by researchers, or being told the turnout of members of the household all increased turnout modestly. But the final treatment---being informed of the turnout of ones neighbors, and an implication that the voter's neighbors would be informed about whether they voted---increased turnout by more than 8 percentage points. In short, the social pressure to vote is considered one of the strongest determinants of whether a citizen casts a ballot.

These social ties, however, are apparently weaker in gentrifying / gentrified neighborhoods. Gentrification can reduce the strength of local churches [@Holmes2020]; the same is true of local businesses [@Zukin2009]. These are the sorts of places where social capital is built; it is perhaps unsurprising, then, Newman, Velez, and Pearson-Merkowitz [-@Newman2016, 340] concludes that "gentrification 'loosens' the social fabric of black communities" and results in lower trust in neighbors and lower reported political engagement, although they recognize the need for "longitudinal and experimental research designs," which their work lacks (341). Similarly, @Betancur2011 traces the dissolution of social network and local institutions in Latino communities in Chicago undergoing gentrification. Gentrification clearly poses a serious threat to the social capital long associated with higher civic participation and may thus lead to lower turnout.

# Administrative Data to Explore Gentrification {-}

Although this project is primarily about the potentially politicizing effect of remaining in, or leaving, a gentrifying neighborhood, it also joins recent scholarship that uses administrative data to understand how gentrification shapes residential mobility patterns in a given region. QUICK OVERVIEW OF THIS LITERATURE

# The Case of Atlanta {-}

This study looks at the case of Atlanta, Georgia, one of the Southeastern United States' major metropolises. I use Atlanta for both theoretical and practical reasons.

In the fall of 2021, Atlantans elected XXX as their new mayor. While the mayoral race dealt with many issues, a central one was gentrification. Local papers such as *The Atlanta Journal-Constitution* [@Capelouto2021] wrote articles in the months leading up the election examining how gentrification could shape the race. Census data released shortly before the election underscored the demographic changes occurring in the city: . Scholars and journalists alike have noted how redevelopment plans and public infrastructure have contributed to gentrification in the city [e.g. @Immergluck2018; @Ashly2020]

For more than a century Atlanta has been considered a major center of Black life in America. W.E.B. Du Bois wrote his 1903 *The Souls of Black Folk* while at Atlanta University; Martin Luther King, Jr., called the city's Ebenezer Baptist Church home for the final years of his life; and Stacey Abrams launched her gubernatorial campaign while representing part of Atlanta in the Georgia General Assembly. Given this history, the racial dynamics at play in the gentrification of Atlanta are particularly salient.

Keisha Lance Bottoms served as mayor for the four years before the 2021 election. Throughout her mayoralty, activists accused her of giving in to real estate developers and doing little to stop gentrification. Spelman students in 2019, for instance, protested her as their commencement speaker over her perceived support for gentrification [@Habersham2019], and in early 2020 a group of Atlanta activists travelled to South Carolina "to question democratic presidential candidate Joe Biden about why his top Georgia Surrogate, Atlanta Mayor Keisha Lance Bottoms, wasn’t doing more to stop low-income black people from being displaced from their homes" [@Deere2020]. In September of 2020, the role of the state in the gentrification of the city was laid bare by a story published in *Mother Jones* [@Thompson2020], in which a former Atlanta Police Department patrol officer said he was directed to arrest Black residents in certain neighborhoods to speed up the gentrification process. Although she created an antidisplacement tax fund to protect homeowners later in 2020 [@Latimore2020], she declined to run for reelection in 2021. THIS SECTION TO BE BEEFED UP AS MORE CONVERSATION ABOUT MAYORAL RACE COMES IN DURING OCTOBER 2021.

Moreover, the politics of Atlanta and its environs hold dramatic import for the rest of the nation, as the 2020 presidential and 2021 U.S. Senate races demonstrated. In 2020, President Joseph Biden carried the Peach State by a slim margin of under 12,000 votes, or just a quarter of a percentage point. Georgia had not been won by a Democratic presidential candidate in a generation, since Bill Clinton carried the state for his first term in 1992. The results of the U.S. Senate races threw this into perhaps even greater relief. Although Georgia had not elected a Democratic U.S. Senator since 1996, *both* of the state's senate seats were captured by Democratic candidates in the runoff election held in January, 2021. The victories of Raphael Warnock and Jon Ossoff resulted in the U.S. Senate being evenly split between Democrats and Republicans, with Vice President Kamala Harris' tie-breaking vote giving the Democrats effective control of the chamber. High turnout in Fulton County---home to Atlanta---was key in each of these races, where Biden's margin over Donald Trump was a quarter-million votes. Warnock and Ossof both similarly outran their competitors in Fulton County by more than 200 thousand votes.

Atlanta also uniquely lends itself to voter file analysis. As discussed in greater depth below, I rely in this study on voter file records to both identify where individuals move and to track their political participation. This necessarily means that I can only observe the behavior of individuals who are registered to vote, a condition that leaves me incapable of following noncitizens through time. Atlanta, however, has a relatively small noncitizen population: according to the Census Bureau, some 94% of the city's population 18 years and older are citizens, contrasting with a median of 90% for the country's 50 largest municipalities.

Of course, many eligible adult citizens throughout the United States are not registered to vote; this too, however, is less common in Georgia than elsewhere. In 2010, roughly 500,000 individuals were registered to vote in Atlanta, out of a full adult population of XX. In other words, approximately 93% of adult Atlantans are registered to vote, a sample size that is an order of magnitude larger than even the broadest former studies [e.g. @Hwang2020]. Thanks to automatic voter registration, which switches registration at the DMV from an opt-in to an opt-out system that hugely increased registration in Georgia [@Morris2019a]. As of 2021, Georgia had one of the highest registration rates in the country, with 95% of adult citizens on the rolls [@Niesse2021a]. Finally, Georgia is also one of just eight states where individuals self-identify their race when they register to vote, allowing me to investigate race-specific effects in this project.

A final feature of Atlanta elections makes it particularly well suited for a project of this sort. The federal system of governance in the United States means that some municipalities hold their local elections in odd-numbered years. These so-called "off-year" elections are characterized by low and uneven turnout without the excitement and spending of federal races available to encourage citizens to vote [see, for instance, @Hajnal2009]. Atlanta is one such city, in which the mayor was most recently elected in November of 2021. While the representational impacts of such off-year elections are concerning, they do allow us to study whether gentrification in Atlanta had unique effects for local and national contests.

# Data and Methods {-}

## Voter File Records {-}

This study primarily leverages administrative voter file records both to identify residents' political engagement and to track their residential mobility over time. In all but one state in the nation, voters are required to register prior to casting a ballot. These records include information including the voter's date of birth; their gender; their address; and, in eight states including Georgia, their self-identified race. Importantly, these files also include unique voter identification numbers that remain constant across time, even when voters move from one county to another. Using near-annual snapshots of these files between 2010 and 2020 (which have been geocoded using the Texas A&M Geocoding Service) I follow residents of Atlanta across time and space.

It is worth noting that the use of the registered voter file marks an important step forward in rigor of our understanding of residential moves in the face of gentrification. In 2010, just shy of a half-million individuals were registered to vote in Atlanta. Such a large sample dwarfs other recent studies. @Hwang2020, for instance, uses the credit records of 50,000 residents of Philadelphia. My sample is thus 10 times as large as theirs---despite the fact that Philadelphia is triple the size of Atlanta. By no means does this undercut the importance of the data used in @Hwang2020; their analysis of household debt and mortgages provides tremendous insight into the financial implications of gentrification. Nevertheless, the fact remains that the voter file data provide an unparalleled look at residential mobility patterns.

To be sure, there are some important drawbacks to the use of these voter file records to interrogate residential mobility. Firstly, there are certain nonrandom selection biases at play: noncitizens, for instance, cannot legally register to vote and are therefore not tracked in this study. Similarly, citizens who are not registered to vote for any reason---whether because they are legally barred from doing so due to a felony conviction or simply do not care for electoral politics---are also excluded from this set. As described in the section above, however, there is reason to believe these biases are less problematic in Georgia, where a smaller share of the adult population are noncitizens and where the registration rate is so high.

There are other potential issues with the use of voter file data. For instance, if an individual moves but does not update her registration, she may appear to still live in her old neighborhood. This too is less likely to be an issue in Georgia, one of only a handful of states with so-called "use it or lose it" voter registration rules. In Georgia, voters can be removed from the rolls for failing to participate in an election and failing to confirm one's address; indeed, Georgia is consistently criticized in the press and by advocacy groups for how aggressively it removes voters from its rolls [e.g. @Kauffman2018; @Amy2021]. It is thus less likely that individuals who have moved in Atlanta will continue to be registered at their old address than in other cities in other American states.

Finally, as with much administrative data, the interpretation of an individual who falls out of the dataset over the study period is not entirely straightforward. There are multiple reasons an individual might have been registered in 2010 but no longer be on the rolls in 2020. They may have died; they may have been convicted of a felony; they may have moved out of the state; or they may have simply withdrawn from the democratic process. Although we cannot tell *why* individuals in Georgia are removed from the voter roll, their absence is nonetheless an important political outcome. Should we find that individuals who lived in gentrifying neighborhoods are disproportionately likely to no longer be registered in 2020, we can still make important conclusions about structural forces pushing these individuals out of the body politic, despite an inability to pinpoint the exact mechanism.

## Methods {-}

I begin by identifying all voters who lived in *potentially* gentrifying neighborhoods in 2010. For this study, I leverage the definition proposed by XXX. Discuss what makes gentrifiable and what makes actually gentrified over the following decade.

I then separate this set of individuals who lived in gentrifiable neighborhoods into two sets: those who lived in neighborhoods that actually went on to gentrify over the next decade, and those who lived in neighborhoods that did not. Voters are considered "treated" if they fall in the first group. Each treated voter is then matched using what methodologists call a "genetic" process [@Sekhon2011] with one voter from the set of potential controls along a battery of observables at both the individual and neighborhood level. Voters are matched according to their turnout in the XXX [each general federal and local election from 2000 to 2010] elections; their age, gender, and race; and the median income and average collegiate attainment from their census tract according to the 2006-2010 5-year ACS survey.

Having identified the pool of all voters "treated" by gentrification and a set of control voters that closely mirror them, I estimate a multinomial logistic regression that tests whether---or where---treated voters move over the ensuing decade, according to the 2020 snapshot of the registered voter file. Specifically, this model asks whether they stayed at the same address; moved, but stayed in the same neighborhood; moved within Atlanta; moved out of Atlanta, but stayed within the state of Georgia; or dropped out of the registered voter file.

After exploring the residential mobility effects of living in a gentrifying neighborhood, I test the treatment effect of living in a gentrifying / gentrified neighborhood of participation in electoral politics. Specifically, I use a difference-in-differences design to test whether the treated individuals became more or less likely to vote---relative to their controls, whose baseline turnout mirrored theirs---over the 2010--2020 period. I also explore whether there is evidence of racial heterogeneity in these treatment effects, and whether moving from or staying in a gentrified neighborhood uniquely (de)politicized residents.

**NB: VAN: I WOULD LIKE YOUR FEEDBACK ON THE FOLLOWING PARAGRAPH. I'M NOT SURE IF I'M UNNECCESSARILY LIMITING MYSELF BY INCLUDING IT. BY MATCHING ON PRE-TREATMENT TURNOUT AND ESTABLISHING THAT THE PARALLEL TRENDS ASSUMPTION IN REASONABLE, I ACTUALLY THINK I CAN MAKE CAUSAL CLAIMS ABOUT THE EFFECT OF LIVING IN A NEIGHBORHOOD THAT GENTRIFIED. THIS SEEMS BETTER SUITED FOR THE DISCUSSION, WHERE I CAN TALK ABOUT LIMITATIONS / WONDER WHETHER TREATED AND CONTROL VOTERS REALLY MIRRORED ONE ANOTHER IN ALL IMPORTANT WAYS. I'M ALSO CHEWING ON WHETHER THE DIFFERENTIAL TIMING OF GENTRIFICATION IN DIFFERENT NEIGHBORHOODS CAN BE LEVERAGED IN INTERESTING WAYS.

It is important to note the limitations to any causal claims available under this analytical framework. Although I will be looking at the outcomes---political and residential---of individuals who mirrored one another according to *observable* characteristics in 2010, there is reason to believe that individuals "treated" by gentrification may have differed in important ways from their respective controls. Gentrification, as discussed extensively above, is a political phenomenon that operates at the neighborhood level; neighborhoods are, of course comprised of their individual residents. Neighborhoods that were gentrifiable---but did not go on to gentrify---may have had more cohesive social networks or stronger community institutions that were able to resist residential turnover; these factors are of course associated with political involvement. The causal claims in this study, therefore, rely on the fairly strict assumption that treated and control voters did not differ in meaningful ways. However, even if we consider this assumption too strong, this project provides insight into the different political trajectories taken by neighborhoods that do and do not gentrify. Finally, because I match treated and control voters on pre-treatment turnout, I am directly controlling for any differences in electoral participation prior to 2010. This should account for any underlying differences in political engagement in the period before one set of voters was treated by gentrification.

\newpage

# References {-}